from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server import util


class ContactPostalInfoEnumType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    LOC = 'loc'
    INT = 'int'
    def __init__(self):  # noqa: E501
        """ContactPostalInfoEnumType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ContactPostalInfoEnumType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The contact_postalInfoEnumType of this ContactPostalInfoEnumType.  # noqa: E501
        :rtype: ContactPostalInfoEnumType
        """
        return util.deserialize_model(dikt, cls)
