from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server import util


class ContactE164Type(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, x=None):  # noqa: E501
        """ContactE164Type - a model defined in OpenAPI

        :param value: The value of this ContactE164Type.  # noqa: E501
        :type value: str
        :param x: The x of this ContactE164Type.  # noqa: E501
        :type x: str
        """
        self.openapi_types = {
            'value': str,
            'x': str
        }

        self.attribute_map = {
            'value': '#value',
            'x': '@x'
        }

        self._value = value
        self._x = x

    @classmethod
    def from_dict(cls, dikt) -> 'ContactE164Type':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The contact_e164Type of this ContactE164Type.  # noqa: E501
        :rtype: ContactE164Type
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this ContactE164Type.


        :return: The value of this ContactE164Type.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ContactE164Type.


        :param value: The value of this ContactE164Type.
        :type value: str
        """
        if value is not None and len(value) > 17:
            raise ValueError("Invalid value for `value`, length must be less than or equal to `17`")  # noqa: E501

        self._value = value

    @property
    def x(self) -> str:
        """Gets the x of this ContactE164Type.


        :return: The x of this ContactE164Type.
        :rtype: str
        """
        return self._x

    @x.setter
    def x(self, x: str):
        """Sets the x of this ContactE164Type.


        :param x: The x of this ContactE164Type.
        :type x: str
        """

        self._x = x
