from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.domain_update_type import DomainUpdateType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.domain_update_type import DomainUpdateType  # noqa: E501

class EppReadWriteTypeOneOf5(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain_update=None):  # noqa: E501
        """EppReadWriteTypeOneOf5 - a model defined in OpenAPI

        :param domain_update: The domain_update of this EppReadWriteTypeOneOf5.  # noqa: E501
        :type domain_update: DomainUpdateType
        """
        self.openapi_types = {
            'domain_update': DomainUpdateType
        }

        self.attribute_map = {
            'domain_update': 'domain_update'
        }

        self._domain_update = domain_update

    @classmethod
    def from_dict(cls, dikt) -> 'EppReadWriteTypeOneOf5':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_readWriteType_oneOf_5 of this EppReadWriteTypeOneOf5.  # noqa: E501
        :rtype: EppReadWriteTypeOneOf5
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_update(self) -> DomainUpdateType:
        """Gets the domain_update of this EppReadWriteTypeOneOf5.


        :return: The domain_update of this EppReadWriteTypeOneOf5.
        :rtype: DomainUpdateType
        """
        return self._domain_update

    @domain_update.setter
    def domain_update(self, domain_update: DomainUpdateType):
        """Sets the domain_update of this EppReadWriteTypeOneOf5.


        :param domain_update: The domain_update of this EppReadWriteTypeOneOf5.
        :type domain_update: DomainUpdateType
        """
        if domain_update is None:
            raise ValueError("Invalid value for `domain_update`, must not be `None`")  # noqa: E501

        self._domain_update = domain_update
