from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.host_inf_data_type import HostInfDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.host_inf_data_type import HostInfDataType  # noqa: E501

class EppExtAnyTypeOneOf8(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, host_inf_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf8 - a model defined in OpenAPI

        :param host_inf_data: The host_inf_data of this EppExtAnyTypeOneOf8.  # noqa: E501
        :type host_inf_data: HostInfDataType
        """
        self.openapi_types = {
            'host_inf_data': HostInfDataType
        }

        self.attribute_map = {
            'host_inf_data': 'host_infData'
        }

        self._host_inf_data = host_inf_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf8':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_8 of this EppExtAnyTypeOneOf8.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf8
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host_inf_data(self) -> HostInfDataType:
        """Gets the host_inf_data of this EppExtAnyTypeOneOf8.


        :return: The host_inf_data of this EppExtAnyTypeOneOf8.
        :rtype: HostInfDataType
        """
        return self._host_inf_data

    @host_inf_data.setter
    def host_inf_data(self, host_inf_data: HostInfDataType):
        """Sets the host_inf_data of this EppExtAnyTypeOneOf8.


        :param host_inf_data: The host_inf_data of this EppExtAnyTypeOneOf8.
        :type host_inf_data: HostInfDataType
        """
        if host_inf_data is None:
            raise ValueError("Invalid value for `host_inf_data`, must not be `None`")  # noqa: E501

        self._host_inf_data = host_inf_data
