from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.domain_info_type import DomainInfoType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.domain_info_type import DomainInfoType  # noqa: E501

class EppReadWriteTypeOneOf3(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain_info=None):  # noqa: E501
        """EppReadWriteTypeOneOf3 - a model defined in OpenAPI

        :param domain_info: The domain_info of this EppReadWriteTypeOneOf3.  # noqa: E501
        :type domain_info: DomainInfoType
        """
        self.openapi_types = {
            'domain_info': DomainInfoType
        }

        self.attribute_map = {
            'domain_info': 'domain_info'
        }

        self._domain_info = domain_info

    @classmethod
    def from_dict(cls, dikt) -> 'EppReadWriteTypeOneOf3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_readWriteType_oneOf_3 of this EppReadWriteTypeOneOf3.  # noqa: E501
        :rtype: EppReadWriteTypeOneOf3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_info(self) -> DomainInfoType:
        """Gets the domain_info of this EppReadWriteTypeOneOf3.


        :return: The domain_info of this EppReadWriteTypeOneOf3.
        :rtype: DomainInfoType
        """
        return self._domain_info

    @domain_info.setter
    def domain_info(self, domain_info: DomainInfoType):
        """Sets the domain_info of this EppReadWriteTypeOneOf3.


        :param domain_info: The domain_info of this EppReadWriteTypeOneOf3.
        :type domain_info: DomainInfoType
        """
        if domain_info is None:
            raise ValueError("Invalid value for `domain_info`, must not be `None`")  # noqa: E501

        self._domain_info = domain_info
