from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.domain_s_name_type import DomainSNameType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.domain_s_name_type import DomainSNameType  # noqa: E501

class EppReadWriteTypeOneOf2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain_delete=None):  # noqa: E501
        """EppReadWriteTypeOneOf2 - a model defined in OpenAPI

        :param domain_delete: The domain_delete of this EppReadWriteTypeOneOf2.  # noqa: E501
        :type domain_delete: DomainSNameType
        """
        self.openapi_types = {
            'domain_delete': DomainSNameType
        }

        self.attribute_map = {
            'domain_delete': 'domain_delete'
        }

        self._domain_delete = domain_delete

    @classmethod
    def from_dict(cls, dikt) -> 'EppReadWriteTypeOneOf2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_readWriteType_oneOf_2 of this EppReadWriteTypeOneOf2.  # noqa: E501
        :rtype: EppReadWriteTypeOneOf2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_delete(self) -> DomainSNameType:
        """Gets the domain_delete of this EppReadWriteTypeOneOf2.


        :return: The domain_delete of this EppReadWriteTypeOneOf2.
        :rtype: DomainSNameType
        """
        return self._domain_delete

    @domain_delete.setter
    def domain_delete(self, domain_delete: DomainSNameType):
        """Sets the domain_delete of this EppReadWriteTypeOneOf2.


        :param domain_delete: The domain_delete of this EppReadWriteTypeOneOf2.
        :type domain_delete: DomainSNameType
        """
        if domain_delete is None:
            raise ValueError("Invalid value for `domain_delete`, must not be `None`")  # noqa: E501

        self._domain_delete = domain_delete
