from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.domain_cre_data_type import DomainCreDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.domain_cre_data_type import DomainCreDataType  # noqa: E501

class EppExtAnyTypeOneOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain_cre_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf1 - a model defined in OpenAPI

        :param domain_cre_data: The domain_cre_data of this EppExtAnyTypeOneOf1.  # noqa: E501
        :type domain_cre_data: DomainCreDataType
        """
        self.openapi_types = {
            'domain_cre_data': DomainCreDataType
        }

        self.attribute_map = {
            'domain_cre_data': 'domain_creData'
        }

        self._domain_cre_data = domain_cre_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_1 of this EppExtAnyTypeOneOf1.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_cre_data(self) -> DomainCreDataType:
        """Gets the domain_cre_data of this EppExtAnyTypeOneOf1.


        :return: The domain_cre_data of this EppExtAnyTypeOneOf1.
        :rtype: DomainCreDataType
        """
        return self._domain_cre_data

    @domain_cre_data.setter
    def domain_cre_data(self, domain_cre_data: DomainCreDataType):
        """Sets the domain_cre_data of this EppExtAnyTypeOneOf1.


        :param domain_cre_data: The domain_cre_data of this EppExtAnyTypeOneOf1.
        :type domain_cre_data: DomainCreDataType
        """
        if domain_cre_data is None:
            raise ValueError("Invalid value for `domain_cre_data`, must not be `None`")  # noqa: E501

        self._domain_cre_data = domain_cre_data
