from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.host_chk_data_type import HostChkDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.host_chk_data_type import HostChkDataType  # noqa: E501

class EppExtAnyTypeOneOf6(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, host_chk_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf6 - a model defined in OpenAPI

        :param host_chk_data: The host_chk_data of this EppExtAnyTypeOneOf6.  # noqa: E501
        :type host_chk_data: HostChkDataType
        """
        self.openapi_types = {
            'host_chk_data': HostChkDataType
        }

        self.attribute_map = {
            'host_chk_data': 'host_chkData'
        }

        self._host_chk_data = host_chk_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf6':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_6 of this EppExtAnyTypeOneOf6.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf6
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host_chk_data(self) -> HostChkDataType:
        """Gets the host_chk_data of this EppExtAnyTypeOneOf6.


        :return: The host_chk_data of this EppExtAnyTypeOneOf6.
        :rtype: HostChkDataType
        """
        return self._host_chk_data

    @host_chk_data.setter
    def host_chk_data(self, host_chk_data: HostChkDataType):
        """Sets the host_chk_data of this EppExtAnyTypeOneOf6.


        :param host_chk_data: The host_chk_data of this EppExtAnyTypeOneOf6.
        :type host_chk_data: HostChkDataType
        """
        if host_chk_data is None:
            raise ValueError("Invalid value for `host_chk_data`, must not be `None`")  # noqa: E501

        self._host_chk_data = host_chk_data
