from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_chk_data_type import ContactChkDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_chk_data_type import ContactChkDataType  # noqa: E501

class EppExtAnyTypeOneOf10(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, contact_chk_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf10 - a model defined in OpenAPI

        :param contact_chk_data: The contact_chk_data of this EppExtAnyTypeOneOf10.  # noqa: E501
        :type contact_chk_data: ContactChkDataType
        """
        self.openapi_types = {
            'contact_chk_data': ContactChkDataType
        }

        self.attribute_map = {
            'contact_chk_data': 'contact_chkData'
        }

        self._contact_chk_data = contact_chk_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf10':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_10 of this EppExtAnyTypeOneOf10.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf10
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_chk_data(self) -> ContactChkDataType:
        """Gets the contact_chk_data of this EppExtAnyTypeOneOf10.


        :return: The contact_chk_data of this EppExtAnyTypeOneOf10.
        :rtype: ContactChkDataType
        """
        return self._contact_chk_data

    @contact_chk_data.setter
    def contact_chk_data(self, contact_chk_data: ContactChkDataType):
        """Sets the contact_chk_data of this EppExtAnyTypeOneOf10.


        :param contact_chk_data: The contact_chk_data of this EppExtAnyTypeOneOf10.
        :type contact_chk_data: ContactChkDataType
        """
        if contact_chk_data is None:
            raise ValueError("Invalid value for `contact_chk_data`, must not be `None`")  # noqa: E501

        self._contact_chk_data = contact_chk_data
