from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_inf_data_type import ContactInfDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_inf_data_type import ContactInfDataType  # noqa: E501

class EppExtAnyTypeOneOf12(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, contact_inf_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf12 - a model defined in OpenAPI

        :param contact_inf_data: The contact_inf_data of this EppExtAnyTypeOneOf12.  # noqa: E501
        :type contact_inf_data: ContactInfDataType
        """
        self.openapi_types = {
            'contact_inf_data': ContactInfDataType
        }

        self.attribute_map = {
            'contact_inf_data': 'contact_infData'
        }

        self._contact_inf_data = contact_inf_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf12':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_12 of this EppExtAnyTypeOneOf12.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf12
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_inf_data(self) -> ContactInfDataType:
        """Gets the contact_inf_data of this EppExtAnyTypeOneOf12.


        :return: The contact_inf_data of this EppExtAnyTypeOneOf12.
        :rtype: ContactInfDataType
        """
        return self._contact_inf_data

    @contact_inf_data.setter
    def contact_inf_data(self, contact_inf_data: ContactInfDataType):
        """Sets the contact_inf_data of this EppExtAnyTypeOneOf12.


        :param contact_inf_data: The contact_inf_data of this EppExtAnyTypeOneOf12.
        :type contact_inf_data: ContactInfDataType
        """
        if contact_inf_data is None:
            raise ValueError("Invalid value for `contact_inf_data`, must not be `None`")  # noqa: E501

        self._contact_inf_data = contact_inf_data
