from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_auth_id_type import ContactAuthIDType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_auth_id_type import ContactAuthIDType  # noqa: E501

class EppReadWriteTypeOneOf14(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, contact_info=None):  # noqa: E501
        """EppReadWriteTypeOneOf14 - a model defined in OpenAPI

        :param contact_info: The contact_info of this EppReadWriteTypeOneOf14.  # noqa: E501
        :type contact_info: ContactAuthIDType
        """
        self.openapi_types = {
            'contact_info': ContactAuthIDType
        }

        self.attribute_map = {
            'contact_info': 'contact_info'
        }

        self._contact_info = contact_info

    @classmethod
    def from_dict(cls, dikt) -> 'EppReadWriteTypeOneOf14':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_readWriteType_oneOf_14 of this EppReadWriteTypeOneOf14.  # noqa: E501
        :rtype: EppReadWriteTypeOneOf14
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_info(self) -> ContactAuthIDType:
        """Gets the contact_info of this EppReadWriteTypeOneOf14.


        :return: The contact_info of this EppReadWriteTypeOneOf14.
        :rtype: ContactAuthIDType
        """
        return self._contact_info

    @contact_info.setter
    def contact_info(self, contact_info: ContactAuthIDType):
        """Sets the contact_info of this EppReadWriteTypeOneOf14.


        :param contact_info: The contact_info of this EppReadWriteTypeOneOf14.
        :type contact_info: ContactAuthIDType
        """
        if contact_info is None:
            raise ValueError("Invalid value for `contact_info`, must not be `None`")  # noqa: E501

        self._contact_info = contact_info
