from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.domain_ren_data_type import DomainRenDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.domain_ren_data_type import DomainRenDataType  # noqa: E501

class EppExtAnyTypeOneOf4(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain_ren_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf4 - a model defined in OpenAPI

        :param domain_ren_data: The domain_ren_data of this EppExtAnyTypeOneOf4.  # noqa: E501
        :type domain_ren_data: DomainRenDataType
        """
        self.openapi_types = {
            'domain_ren_data': DomainRenDataType
        }

        self.attribute_map = {
            'domain_ren_data': 'domain_renData'
        }

        self._domain_ren_data = domain_ren_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf4':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_4 of this EppExtAnyTypeOneOf4.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf4
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_ren_data(self) -> DomainRenDataType:
        """Gets the domain_ren_data of this EppExtAnyTypeOneOf4.


        :return: The domain_ren_data of this EppExtAnyTypeOneOf4.
        :rtype: DomainRenDataType
        """
        return self._domain_ren_data

    @domain_ren_data.setter
    def domain_ren_data(self, domain_ren_data: DomainRenDataType):
        """Sets the domain_ren_data of this EppExtAnyTypeOneOf4.


        :param domain_ren_data: The domain_ren_data of this EppExtAnyTypeOneOf4.
        :type domain_ren_data: DomainRenDataType
        """
        if domain_ren_data is None:
            raise ValueError("Invalid value for `domain_ren_data`, must not be `None`")  # noqa: E501

        self._domain_ren_data = domain_ren_data
