from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_auth_info_type import ContactAuthInfoType
from rpp_py_flask_server.models.contact_chg_postal_info_type import ContactChgPostalInfoType
from rpp_py_flask_server.models.contact_disclose_type import ContactDiscloseType
from rpp_py_flask_server.models.contact_e164_type import ContactE164Type
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_auth_info_type import ContactAuthInfoType  # noqa: E501
from rpp_py_flask_server.models.contact_chg_postal_info_type import ContactChgPostalInfoType  # noqa: E501
from rpp_py_flask_server.models.contact_disclose_type import ContactDiscloseType  # noqa: E501
from rpp_py_flask_server.models.contact_e164_type import ContactE164Type  # noqa: E501

class ContactChgType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, auth_info=None, disclose=None, email=None, fax=None, postal_info=None, voice=None):  # noqa: E501
        """ContactChgType - a model defined in OpenAPI

        :param auth_info: The auth_info of this ContactChgType.  # noqa: E501
        :type auth_info: ContactAuthInfoType
        :param disclose: The disclose of this ContactChgType.  # noqa: E501
        :type disclose: ContactDiscloseType
        :param email: The email of this ContactChgType.  # noqa: E501
        :type email: str
        :param fax: The fax of this ContactChgType.  # noqa: E501
        :type fax: ContactE164Type
        :param postal_info: The postal_info of this ContactChgType.  # noqa: E501
        :type postal_info: List[ContactChgPostalInfoType]
        :param voice: The voice of this ContactChgType.  # noqa: E501
        :type voice: ContactE164Type
        """
        self.openapi_types = {
            'auth_info': ContactAuthInfoType,
            'disclose': ContactDiscloseType,
            'email': str,
            'fax': ContactE164Type,
            'postal_info': List[ContactChgPostalInfoType],
            'voice': ContactE164Type
        }

        self.attribute_map = {
            'auth_info': 'authInfo',
            'disclose': 'disclose',
            'email': 'email',
            'fax': 'fax',
            'postal_info': 'postalInfo',
            'voice': 'voice'
        }

        self._auth_info = auth_info
        self._disclose = disclose
        self._email = email
        self._fax = fax
        self._postal_info = postal_info
        self._voice = voice

    @classmethod
    def from_dict(cls, dikt) -> 'ContactChgType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The contact_chgType of this ContactChgType.  # noqa: E501
        :rtype: ContactChgType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def auth_info(self) -> ContactAuthInfoType:
        """Gets the auth_info of this ContactChgType.


        :return: The auth_info of this ContactChgType.
        :rtype: ContactAuthInfoType
        """
        return self._auth_info

    @auth_info.setter
    def auth_info(self, auth_info: ContactAuthInfoType):
        """Sets the auth_info of this ContactChgType.


        :param auth_info: The auth_info of this ContactChgType.
        :type auth_info: ContactAuthInfoType
        """

        self._auth_info = auth_info

    @property
    def disclose(self) -> ContactDiscloseType:
        """Gets the disclose of this ContactChgType.


        :return: The disclose of this ContactChgType.
        :rtype: ContactDiscloseType
        """
        return self._disclose

    @disclose.setter
    def disclose(self, disclose: ContactDiscloseType):
        """Sets the disclose of this ContactChgType.


        :param disclose: The disclose of this ContactChgType.
        :type disclose: ContactDiscloseType
        """

        self._disclose = disclose

    @property
    def email(self) -> str:
        """Gets the email of this ContactChgType.


        :return: The email of this ContactChgType.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this ContactChgType.


        :param email: The email of this ContactChgType.
        :type email: str
        """
        if email is not None and len(email) < 1:
            raise ValueError("Invalid value for `email`, length must be greater than or equal to `1`")  # noqa: E501

        self._email = email

    @property
    def fax(self) -> ContactE164Type:
        """Gets the fax of this ContactChgType.


        :return: The fax of this ContactChgType.
        :rtype: ContactE164Type
        """
        return self._fax

    @fax.setter
    def fax(self, fax: ContactE164Type):
        """Sets the fax of this ContactChgType.


        :param fax: The fax of this ContactChgType.
        :type fax: ContactE164Type
        """

        self._fax = fax

    @property
    def postal_info(self) -> List[ContactChgPostalInfoType]:
        """Gets the postal_info of this ContactChgType.


        :return: The postal_info of this ContactChgType.
        :rtype: List[ContactChgPostalInfoType]
        """
        return self._postal_info

    @postal_info.setter
    def postal_info(self, postal_info: List[ContactChgPostalInfoType]):
        """Sets the postal_info of this ContactChgType.


        :param postal_info: The postal_info of this ContactChgType.
        :type postal_info: List[ContactChgPostalInfoType]
        """
        if postal_info is not None and len(postal_info) > 2:
            raise ValueError("Invalid value for `postal_info`, number of items must be less than or equal to `2`")  # noqa: E501
        if postal_info is not None and len(postal_info) < 0:
            raise ValueError("Invalid value for `postal_info`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._postal_info = postal_info

    @property
    def voice(self) -> ContactE164Type:
        """Gets the voice of this ContactChgType.


        :return: The voice of this ContactChgType.
        :rtype: ContactE164Type
        """
        return self._voice

    @voice.setter
    def voice(self, voice: ContactE164Type):
        """Sets the voice of this ContactChgType.


        :param voice: The voice of this ContactChgType.
        :type voice: ContactE164Type
        """

        self._voice = voice
