from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_check_type import ContactCheckType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_check_type import ContactCheckType  # noqa: E501

class ContactChkDataType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cd=None):  # noqa: E501
        """ContactChkDataType - a model defined in OpenAPI

        :param cd: The cd of this ContactChkDataType.  # noqa: E501
        :type cd: List[ContactCheckType]
        """
        self.openapi_types = {
            'cd': List[ContactCheckType]
        }

        self.attribute_map = {
            'cd': 'cd'
        }

        self._cd = cd

    @classmethod
    def from_dict(cls, dikt) -> 'ContactChkDataType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The contact_chkDataType of this ContactChkDataType.  # noqa: E501
        :rtype: ContactChkDataType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cd(self) -> List[ContactCheckType]:
        """Gets the cd of this ContactChkDataType.


        :return: The cd of this ContactChkDataType.
        :rtype: List[ContactCheckType]
        """
        return self._cd

    @cd.setter
    def cd(self, cd: List[ContactCheckType]):
        """Sets the cd of this ContactChkDataType.


        :param cd: The cd of this ContactChkDataType.
        :type cd: List[ContactCheckType]
        """
        if cd is None:
            raise ValueError("Invalid value for `cd`, must not be `None`")  # noqa: E501
        if cd is not None and len(cd) < 1:
            raise ValueError("Invalid value for `cd`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._cd = cd
