from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_trn_data_type import ContactTrnDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_trn_data_type import ContactTrnDataType  # noqa: E501

class EppExtAnyTypeOneOf14(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, contact_trn_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf14 - a model defined in OpenAPI

        :param contact_trn_data: The contact_trn_data of this EppExtAnyTypeOneOf14.  # noqa: E501
        :type contact_trn_data: ContactTrnDataType
        """
        self.openapi_types = {
            'contact_trn_data': ContactTrnDataType
        }

        self.attribute_map = {
            'contact_trn_data': 'contact_trnData'
        }

        self._contact_trn_data = contact_trn_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf14':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_14 of this EppExtAnyTypeOneOf14.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf14
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_trn_data(self) -> ContactTrnDataType:
        """Gets the contact_trn_data of this EppExtAnyTypeOneOf14.


        :return: The contact_trn_data of this EppExtAnyTypeOneOf14.
        :rtype: ContactTrnDataType
        """
        return self._contact_trn_data

    @contact_trn_data.setter
    def contact_trn_data(self, contact_trn_data: ContactTrnDataType):
        """Sets the contact_trn_data of this EppExtAnyTypeOneOf14.


        :param contact_trn_data: The contact_trn_data of this EppExtAnyTypeOneOf14.
        :type contact_trn_data: ContactTrnDataType
        """
        if contact_trn_data is None:
            raise ValueError("Invalid value for `contact_trn_data`, must not be `None`")  # noqa: E501

        self._contact_trn_data = contact_trn_data
