from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.contact_mid_type import ContactMIDType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.contact_mid_type import ContactMIDType  # noqa: E501

class EppReadWriteTypeOneOf11(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, contact_check=None):  # noqa: E501
        """EppReadWriteTypeOneOf11 - a model defined in OpenAPI

        :param contact_check: The contact_check of this EppReadWriteTypeOneOf11.  # noqa: E501
        :type contact_check: ContactMIDType
        """
        self.openapi_types = {
            'contact_check': ContactMIDType
        }

        self.attribute_map = {
            'contact_check': 'contact_check'
        }

        self._contact_check = contact_check

    @classmethod
    def from_dict(cls, dikt) -> 'EppReadWriteTypeOneOf11':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_readWriteType_oneOf_11 of this EppReadWriteTypeOneOf11.  # noqa: E501
        :rtype: EppReadWriteTypeOneOf11
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_check(self) -> ContactMIDType:
        """Gets the contact_check of this EppReadWriteTypeOneOf11.


        :return: The contact_check of this EppReadWriteTypeOneOf11.
        :rtype: ContactMIDType
        """
        return self._contact_check

    @contact_check.setter
    def contact_check(self, contact_check: ContactMIDType):
        """Sets the contact_check of this EppReadWriteTypeOneOf11.


        :param contact_check: The contact_check of this EppReadWriteTypeOneOf11.
        :type contact_check: ContactMIDType
        """
        if contact_check is None:
            raise ValueError("Invalid value for `contact_check`, must not be `None`")  # noqa: E501

        self._contact_check = contact_check
