from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.host_cre_data_type import HostCreDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.host_cre_data_type import HostCreDataType  # noqa: E501

class EppExtAnyTypeOneOf7(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, host_cre_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf7 - a model defined in OpenAPI

        :param host_cre_data: The host_cre_data of this EppExtAnyTypeOneOf7.  # noqa: E501
        :type host_cre_data: HostCreDataType
        """
        self.openapi_types = {
            'host_cre_data': HostCreDataType
        }

        self.attribute_map = {
            'host_cre_data': 'host_creData'
        }

        self._host_cre_data = host_cre_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf7':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_7 of this EppExtAnyTypeOneOf7.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf7
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host_cre_data(self) -> HostCreDataType:
        """Gets the host_cre_data of this EppExtAnyTypeOneOf7.


        :return: The host_cre_data of this EppExtAnyTypeOneOf7.
        :rtype: HostCreDataType
        """
        return self._host_cre_data

    @host_cre_data.setter
    def host_cre_data(self, host_cre_data: HostCreDataType):
        """Sets the host_cre_data of this EppExtAnyTypeOneOf7.


        :param host_cre_data: The host_cre_data of this EppExtAnyTypeOneOf7.
        :type host_cre_data: HostCreDataType
        """
        if host_cre_data is None:
            raise ValueError("Invalid value for `host_cre_data`, must not be `None`")  # noqa: E501

        self._host_cre_data = host_cre_data
