from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.domain_pan_data_type import DomainPanDataType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.domain_pan_data_type import DomainPanDataType  # noqa: E501

class EppExtAnyTypeOneOf3(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain_pan_data=None):  # noqa: E501
        """EppExtAnyTypeOneOf3 - a model defined in OpenAPI

        :param domain_pan_data: The domain_pan_data of this EppExtAnyTypeOneOf3.  # noqa: E501
        :type domain_pan_data: DomainPanDataType
        """
        self.openapi_types = {
            'domain_pan_data': DomainPanDataType
        }

        self.attribute_map = {
            'domain_pan_data': 'domain_panData'
        }

        self._domain_pan_data = domain_pan_data

    @classmethod
    def from_dict(cls, dikt) -> 'EppExtAnyTypeOneOf3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_extAnyType_oneOf_3 of this EppExtAnyTypeOneOf3.  # noqa: E501
        :rtype: EppExtAnyTypeOneOf3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_pan_data(self) -> DomainPanDataType:
        """Gets the domain_pan_data of this EppExtAnyTypeOneOf3.


        :return: The domain_pan_data of this EppExtAnyTypeOneOf3.
        :rtype: DomainPanDataType
        """
        return self._domain_pan_data

    @domain_pan_data.setter
    def domain_pan_data(self, domain_pan_data: DomainPanDataType):
        """Sets the domain_pan_data of this EppExtAnyTypeOneOf3.


        :param domain_pan_data: The domain_pan_data of this EppExtAnyTypeOneOf3.
        :type domain_pan_data: DomainPanDataType
        """
        if domain_pan_data is None:
            raise ValueError("Invalid value for `domain_pan_data`, must not be `None`")  # noqa: E501

        self._domain_pan_data = domain_pan_data
