from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpp_py_flask_server.models.base_model import Model
from rpp_py_flask_server.models.host_create_type import HostCreateType
from rpp_py_flask_server import util

from rpp_py_flask_server.models.host_create_type import HostCreateType  # noqa: E501

class EppReadWriteTypeOneOf7(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, host_create=None):  # noqa: E501
        """EppReadWriteTypeOneOf7 - a model defined in OpenAPI

        :param host_create: The host_create of this EppReadWriteTypeOneOf7.  # noqa: E501
        :type host_create: HostCreateType
        """
        self.openapi_types = {
            'host_create': HostCreateType
        }

        self.attribute_map = {
            'host_create': 'host_create'
        }

        self._host_create = host_create

    @classmethod
    def from_dict(cls, dikt) -> 'EppReadWriteTypeOneOf7':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_readWriteType_oneOf_7 of this EppReadWriteTypeOneOf7.  # noqa: E501
        :rtype: EppReadWriteTypeOneOf7
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host_create(self) -> HostCreateType:
        """Gets the host_create of this EppReadWriteTypeOneOf7.


        :return: The host_create of this EppReadWriteTypeOneOf7.
        :rtype: HostCreateType
        """
        return self._host_create

    @host_create.setter
    def host_create(self, host_create: HostCreateType):
        """Sets the host_create of this EppReadWriteTypeOneOf7.


        :param host_create: The host_create of this EppReadWriteTypeOneOf7.
        :type host_create: HostCreateType
        """
        if host_create is None:
            raise ValueError("Invalid value for `host_create`, must not be `None`")  # noqa: E501

        self._host_create = host_create
